language: python
os: linux
dist: bionic
python:
  - "3.8"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv
install:
  - "export WOKON_HOME=.pipenv/venvs"
  - "export PIP_CACHE_DIR=.pipenv/pipcache"
  - "pip install pipenv"
  - "pipenv install --dev"
script: "pipenv run python -m pytest"
